export const products = [
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone XL',
    price: 799,
    description: 'A large phone with one of the best screens',
    heading1: 'sample text1',
    heading2: 'sample text2',
    heading3: 'sample text3',
    headingtext1: 'sample message1',
    headingtext2: 'sample message2',
    headingtext3: 'sample message3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Mini',
    price: 699,
    description: 'A great phone with one of the best cameras',
    heading1: 'sample text1',
    heading2: 'sample text2',
    heading3: 'sample text3',
    headingtext1: 'sample message1',
    headingtext2: 'sample message2',
    headingtext3: 'sample message3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Standard',
    price: 299,
    description: '',
    heading1: 'sample text1',
    heading2: 'sample text2',
    heading3: 'sample text3',
    headingtext1: 'sample message1',
    headingtext2: 'sample message2',
    headingtext3: 'sample message3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Special',
    price: 99,
    description: '',
    heading1: 'sample text1',
    heading2: 'sample text2',
    heading3: 'sample text3',
    headingtext1: 'sample message1',
    headingtext2: 'sample message2',
    headingtext3: 'sample message3',
  }
];
